{% set name = "spylon" %}
{% set version = "0.2.10" %}
{% set hashtype = "sha256" %}
{% set hash = "776643a622b85f6cca65f7e67c8517b8d1e39d540079c17c2a575c9df3dbdf58" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  {{ hashtype }}: {{ hash }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt
  entry_points:
    - pyspark_yarn_client_conda=spylon.spark.yarn_launcher:pyspark_conda_yarn_client
    - pyspark_yarn_cluster_conda=spylon.spark.yarn_launcher:pyspark_conda_yarn_cluster

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - findspark
    - pyyaml
    - six

test:
  imports:
    - spylon
    - spylon.spark
    - spylon.spark.yarn_launcher

about:
  home: https://github.com/MaxPoint/spylon
  license: BSD 3-clause
  summary: Utilities to work with Scala/Java code with py4j

extra:
  recipe-maintainers:
    - mariusvniekerk
    - ericdill
    - parente
