{% set name = "spylon" %}
{% set version = "0.2.0" %}
{% set hashtype = "md5" %}
{% set hash = "53490a409a40132fa37ae1722276bbee" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  {{ hashtype }}: {{ hash }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - findspark
    - pandas

test:
  imports:
    - spylon
    - spylon.spark

about:
  home: https://github.com/MaxPoint/spylon
  license: BSD 3-clause
  summary: Utilities to work with Scala/Java code with py4j

extra:
  recipe-maintainers:
    - mariusvniekerk
