{% set name = "spylon" %}
{% set version = "0.3.0" %}
{% set hashtype = "sha256" %}
{% set hash = '104b9bf7a28c15c27b3c3dcba199f847b93f09b78e97f15e0a0bcac3cbb0bbe4' %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  {{ hashtype }}: {{ hash }}

build:
  noarch: python
  number: 1
  script: python -m pip install --no-deps --ignore-installed .
  entry_points:
    - pyspark_yarn_client_conda=spylon.spark.yarn_launcher:pyspark_conda_yarn_client
    - pyspark_yarn_cluster_conda=spylon.spark.yarn_launcher:pyspark_conda_yarn_cluster

requirements:
  host:
    - pip
    - python
    - setuptools

  run:
    - python
    - findspark
    - pyyaml
    - six

test:
  imports:
    - spylon
    - spylon.spark
    - spylon.spark.yarn_launcher

about:
  home: https://github.com/MaxPoint/spylon
  license: BSD 3-clause
  summary: Utilities to work with Scala/Java code with py4j

extra:
  recipe-maintainers:
    - mariusvniekerk
    - parente
