# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=35
    - CONDA_PY=36
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "BO0ooF94k6Mk1lX2Tp50p3O9NTD1r9syoe4hdJUQsBRweCo0HeKrkAK+lLtb0xWS23ErN5uY7TRyPQECjV0JHwqq87qOmaaJOGkwFrinxW8P5v2DWR5BNN1tOvs3UEEzueqSQb7Fr/Z8mwil0fGdvqD1zEYOQb3xLVsjNOLIxjySsrjyOekzEu21nBHbvhSoHp6iGSw/Nkf736ZKradhoysIydKXiLn6N5/WNkmR2eb9Jvpdkzq9hybjfHo2KHKYjRbuVezZeyuSOXpskNbxUUOjK1l6T1bWXOAC4doMU7Pag7APJVjRjXM7L46tqdUxgCLRIalylCGO4hI6Zw2EGNvmPcsYBr9ZKJTKzepKGuTx05/68xx3XFNafDhLlc390daYeMCvU3NSFRfGITL8UD/DCES/oOl3OBnyWRvd1TbGm7Fm1H7psjTkasMw07w/NVJsEBeMHe18eKXUGsNLsLVLnNo9qF26VzGKFTZJ6hvKp5BcR0aGgCZcxUqUIIVpwYiToxdsQszoxrjqLH4U9v28FMfThGLnYpOGnL67Cn1rf5Qh+A8Ed3Y50uC86bg3fCONrLzNo2in+1T3tbSRycVpNRc7LXAPfmwk0QGYuab1Nu0jK0MlerCm9M4ymno1Iz6a8hWwN95xu09T2dsHRn7HulRrps3O0SGVzIyn7Vg="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
