travis:
  secure:
    BINSTAR_TOKEN: ON7EAnSUjZNYu/uBVn0eENArKRVSUjRFgS2mYF6og5YRBRld9MW4dUnWhipIHZZ145Qgjo/ObkpV/7eeDY9i0NX7HEhuQypY0YOOrJ/5Walg2Y/a8vaYIiA1dPgYYpqIo9MHR3e57/9PGWzhicHfve9JWIUCfBPnzzSN7+8AhcmDTEUa/43oQqJQ5syGpgaPsHqBxbNe/4iaw7F2xoSf8ilrl6WtJhjlkcRP2OBKRsR+ChtQTUD1SQ3/FB6OTOYzPNzeQaXo8U9dL5tsZTGrIxCuvvQNwXHN7bO0LCgsjpYfXCpOrlrbF+XFNcCBTxZ9t1tX9UxlWHuUqLa3C1Lu/8AxyYwNbQI4fCgIlHlXOq5ZNKC7btXevyb8fEySuGJGMkyN5ofbjSUhMNhYXFJg0ENbzKBSg7AOg3TVwvvy3mQcOkBdB5Kg3I1SCeScXsO/VxjeDJN/RiCXyMAZVQ27UVL+b9510+obIgT9tmUZ9A0RBoCG/nlHALprLfWq6CIBcMhtGG+yjWXkpnP/CwS3+sON8VVUp+f5cpjv8tqXUq6WhdginVwxhkGsF/OLpL+oDlhizbRCFxjgBGEw22WUgC1VevGUVm8E0kVvLZvamBeAVKgwSwvDPzPy0ygy/qbA5OHHncyzrjuiCF8CmiFmIP74ArhR89uA2H8Dhaan2BU=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: false
