travis:
  secure:
    BINSTAR_TOKEN: BO0ooF94k6Mk1lX2Tp50p3O9NTD1r9syoe4hdJUQsBRweCo0HeKrkAK+lLtb0xWS23ErN5uY7TRyPQECjV0JHwqq87qOmaaJOGkwFrinxW8P5v2DWR5BNN1tOvs3UEEzueqSQb7Fr/Z8mwil0fGdvqD1zEYOQb3xLVsjNOLIxjySsrjyOekzEu21nBHbvhSoHp6iGSw/Nkf736ZKradhoysIydKXiLn6N5/WNkmR2eb9Jvpdkzq9hybjfHo2KHKYjRbuVezZeyuSOXpskNbxUUOjK1l6T1bWXOAC4doMU7Pag7APJVjRjXM7L46tqdUxgCLRIalylCGO4hI6Zw2EGNvmPcsYBr9ZKJTKzepKGuTx05/68xx3XFNafDhLlc390daYeMCvU3NSFRfGITL8UD/DCES/oOl3OBnyWRvd1TbGm7Fm1H7psjTkasMw07w/NVJsEBeMHe18eKXUGsNLsLVLnNo9qF26VzGKFTZJ6hvKp5BcR0aGgCZcxUqUIIVpwYiToxdsQszoxrjqLH4U9v28FMfThGLnYpOGnL67Cn1rf5Qh+A8Ed3Y50uC86bg3fCONrLzNo2in+1T3tbSRycVpNRc7LXAPfmwk0QGYuab1Nu0jK0MlerCm9M4ymno1Iz6a8hWwN95xu09T2dsHRn7HulRrps3O0SGVzIyn7Vg=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
